
import { AssetStatus, AssetType, TokenAsset } from './types';

export const MOCK_ASSETS: TokenAsset[] = [
  {
    id: 'ASEAN-PURA-03',
    name: 'ASEAN Organic EU Import Pool',
    type: AssetType.AGRICULTURE,
    status: AssetStatus.FUNDING,
    yieldPa: 6.8,
    duration: 9,
    minInvestment: 1000,
    totalRaising: 5000000,
    raised: 2100000,
    rating: 'AA+',
    isVeriPura: true,
    description: 'A pool of multiple importers of EU Certified Organic Food Products from the ASEAN region. All documentation and traceability have been VeriPura validated, ensuring a lower risk profile and institutional-grade security.',
    issuer: 'VeriPura Solutions Gmbh.',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'ALDI-SUP-POOL-04',
    name: 'Retail Leader (Aldi-Chain) Supplier Payables',
    type: AssetType.AGRICULTURE,
    status: AssetStatus.FUNDING,
    yieldPa: 8.2,
    duration: 6,
    minInvestment: 500,
    totalRaising: 3000000,
    raised: 1100000,
    rating: 'AA-',
    isVeriPura: true,
    description: 'A diversified pool of receivables owed by major retail chain branches to their verified organic and processed food suppliers. Features credit enhancement via top-tier trade credit insurance and VeriPura document validation.',
    issuer: 'VeriLiquid Retail Securitization S.A.',
    image: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?auto=format&fit=crop&q=80&w=1200'
  },
  {
    id: 'AFG-PROC-POOL-05',
    name: 'Asian Food Group (AFG) Processor Fund',
    type: AssetType.FIXED_INCOME,
    status: AssetStatus.FUNDING,
    yieldPa: 10.5,
    duration: 12,
    minInvestment: 1000,
    totalRaising: 4500000,
    raised: 2800000,
    rating: 'A',
    description: 'A financing facility for Southeast Asian processors supplying high-value specialty ingredients to major European food importers. Validated farm-to-factory documentation and shipment milestones included in the VeriPura evidence pack.',
    issuer: 'AFG Trade Finance Partners',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=1200'
  },
  {
    id: 'SRP-RICE-POOL-06',
    name: 'Sustainable Rice Platform (SRP) Importers',
    type: AssetType.AGRICULTURE,
    status: AssetStatus.FUNDING,
    yieldPa: 7.9,
    duration: 9,
    minInvestment: 250,
    totalRaising: 2000000,
    raised: 450000,
    rating: 'A+',
    isVeriPura: true,
    description: 'A dedicated pool of short-term receivables for European importers of SRP-certified sustainable rice. Direct digital links to environmental impact logs, greenhouse gas emission reduction data, and verified smallholder traceability.',
    issuer: 'GreenGrain Settlement Hub S.A.',
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&q=80&w=1200',
    certificateLogo: 'https://sustainablerice.org/wp-content/uploads/2020/06/SRP-Logo.png'
  },
  {
    id: 'TIDC-LOGI-01',
    name: 'LogiLink Logistics Debt I',
    type: AssetType.FIXED_INCOME,
    status: AssetStatus.ACTIVE,
    yieldPa: 11.2,
    duration: 18,
    minInvestment: 100,
    totalRaising: 1500000,
    raised: 1500000,
    rating: 'A-',
    description: 'A receivables-backed security for LogiLink EU, focusing on cross-border logistics infrastructure in Western Europe.',
    issuer: 'LogiLink Securitizations S.A.',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'RFA-TRADE-02',
    name: 'Rainforest Alliance Trade Fund',
    type: AssetType.FIXED_INCOME,
    status: AssetStatus.ACTIVE,
    yieldPa: 9.5,
    duration: 12,
    minInvestment: 100,
    totalRaising: 2500000,
    raised: 2500000,
    rating: 'A',
    description: 'A dedicated fund of trade payables for Rainforest Alliance Certified Products. This fund supports sustainable supply chains for cocoa, coffee, and tea, ensuring fair value and biodiversity protection.',
    issuer: 'EcoEquity Trade Finance S.A.',
    image: 'https://images.unsplash.com/photo-1534067783941-51c9c23ecefd?auto=format&fit=crop&q=80&w=1200',
    certificateLogo: 'https://upload.wikimedia.org/wikipedia/en/3/36/Rainforest_Alliance_logo.svg'
  }
];
